uiConstants = {
  LAYER_BLOCKER = "blocker",
  LAYER_BLOCKER_PRIORITY = 1,
  
  LAYER_MAIN_MENU = "mainMenu",
  LAYER_MAIN_MENU_PRIORITY = 10,
  
  LAYER_OPTIONS = "options",
  LAYER_OPTIONS_PRIORITY = 11,

  MENU_OPTION_LINE_HEIGHT = 14,
  MENU_OPTION_START_X_PCT = .5,
  MENU_OPTION_START_Y_PCT = .667, --Center menu options around here

  COLOR_DEFAULT = {192, 192, 192, 255},
  COLOR_MENU_SELECTED = {255, 255, 255, 255}
}